[uwsgi]
chdir               = /home/amos/treeline
module              = treeline.wsgi:application
virtualenv          = /home/amos/treeline/.venv

master              = true
processes           = 6
harakiri            = 600
post-buffering      = 4096
enable-threads      = true
logto               = /home/amos/treeline/treeline.log
socket              = /var/uwsgi/treeline.sock

chown-socket        = amos
chgrp-socket        = amos
chmod-socket        = 660
vacuum              = true
thunder-lock        = true

uid                 = amos
gid                 = amos
