# Generated by Django 6.0.4 on 2026-04-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('full_name', models.CharField(max_length=255, unique=True)),
                ('english_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso639_1', models.SlugField(max_length=2, unique=True)),
                ('iso639_3', models.SlugField(blank=True, max_length=3, null=True, unique=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('english_name', models.CharField(max_length=64, unique=True)),
                ('priority', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['priority', 'english_name'],
            },
        ),
    ]
