# Generated by Django 6.0.4 on 2026-04-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='country_code',
            field=models.SlugField(default='uk', max_length=2),
            preserve_default=False,
        ),
    ]
