# Generated by Django 6.0.5 on 2026-05-10 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_language_country_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'Countries'},
        ),
    ]
