# Generated by Django 6.0.4 on 2026-04-18 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('quality', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NamedPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('country', models.ManyToManyField(to='core.country')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mountains.source')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Col',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mountains.namedpoint')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='mountains.namedpoint')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PointName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('local', models.BooleanField(default=False)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.language')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='mountains.namedpoint')),
            ],
        ),
        migrations.CreateModel(
            name='Summit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('island_high_point', models.BooleanField(default=False)),
                ('isolation_name', models.CharField(blank=True, max_length=64, null=True)),
                ('isolation_latitude', models.FloatField(blank=True, help_text='The exact latitude of the nearest highest point', null=True)),
                ('isolation_longitude', models.FloatField(blank=True, help_text='The exact longitude of the nearest highest point', null=True)),
                ('encirclement_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encirclement_children', to='mountains.summit')),
                ('isolation_parent', models.ForeignKey(blank=True, help_text='The nearest significant summit higher than this.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isolation_for', to='mountains.summit')),
                ('isolation_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isolation_data', to='mountains.source')),
                ('key_col', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='key_for', to='mountains.col')),
                ('point', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mountains.namedpoint')),
                ('prominence_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prominence_children', to='mountains.summit')),
                ('prominence_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prominence_data', to='mountains.source')),
            ],
            options={
                'ordering': ('-point__altitude',),
            },
        ),
    ]
