# Generated by Django 6.0.4 on 2026-05-01 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summit',
            name='isolation_parent',
            field=models.ForeignKey(blank=True, help_text='The nearest significant summit higher than this.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='isolation_children', to='mountains.summit'),
        ),
        migrations.CreateModel(
            name='Confluence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mountains.namedpoint')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='col',
            name='confluence',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mountains.confluence'),
        ),
    ]
