# Generated by Django 6.0.4 on 2026-05-01 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0002_alter_summit_isolation_parent_confluence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='col',
            name='confluence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mountains.confluence'),
        ),
    ]
