# Generated by Django 6.0.4 on 2026-05-04 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0003_alter_col_confluence'),
    ]

    operations = [
        migrations.AddField(
            model_name='summit',
            name='slope_parent',
            field=models.ForeignKey(blank=True, help_text='The summit with highest ratio of elevation change over distance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slope_children', to='mountains.summit'),
        ),
        migrations.AddField(
            model_name='summit',
            name='slope_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slope_data', to='mountains.source'),
        ),
        migrations.AlterField(
            model_name='col',
            name='confluence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cols', to='mountains.confluence'),
        ),
    ]
