# Generated by Django 6.0.4 on 2026-05-07 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0004_summit_slope_parent_summit_slope_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summit',
            name='slope_source',
        ),
        migrations.AddField(
            model_name='summit',
            name='horizon_parent',
            field=models.ForeignKey(blank=True, help_text='The summit that is the highest point above the local horizon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horizon_children', to='mountains.summit'),
        ),
    ]
