# Generated by Django 6.0.5 on 2026-05-10 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0005_remove_summit_slope_source_summit_horizon_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='namedpoint',
            old_name='country',
            new_name='countries',
        ),
    ]
