# Generated by Django 6.0.5 on 2026-05-11 12:33

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0006_rename_country_namedpoint_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='namedpoint',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
