# Generated by Django 6.0.5 on 2026-05-11 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0009_summit_nearest_highest_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointname',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mountains.source'),
        ),
    ]
