# Generated by Django 6.0.5 on 2026-05-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0010_pointname_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namedpoint',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
