# Generated by Django 6.0.5 on 2026-05-12 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0012_river'),
    ]

    operations = [
        migrations.AddField(
            model_name='col',
            name='confluence_river',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cols', to='mountains.river'),
        ),
    ]
