# Generated by Django 6.0.5 on 2026-05-13 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0013_col_confluence_river'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='river',
            name='mouth',
        ),
    ]
