# Generated by Django 6.0.5 on 2026-05-13 08:12

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0014_remove_river_mouth'),
    ]

    operations = [
        migrations.AddField(
            model_name='river',
            name='mouth',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
