# Generated by Django 6.0.5 on 2026-05-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0015_river_mouth'),
    ]

    operations = [
        migrations.AddField(
            model_name='river',
            name='mouth_altitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
