# Generated by Django 6.0.5 on 2026-05-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0016_river_mouth_altitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namedpoint',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='namedpoint',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
