# Generated by Django 6.0.5 on 2026-05-15 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0017_alter_namedpoint_latitude_alter_namedpoint_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summit',
            name='isolation_latitude',
        ),
        migrations.RemoveField(
            model_name='summit',
            name='isolation_longitude',
        ),
        migrations.AddField(
            model_name='river',
            name='summit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rivers', to='mountains.summit'),
        ),
    ]
