# Generated by Django 6.0.5 on 2026-05-15 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0018_remove_summit_isolation_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summit',
            old_name='nearest_highest_point',
            new_name='nearest_higher_point',
        ),
    ]
