# Generated by Django 6.0.5 on 2026-05-15 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0019_rename_nearest_highest_point_summit_nearest_higher_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='namedpoint',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='namedpoint',
            name='longitude',
        ),
    ]
