# Generated by Django 6.0.5 on 2026-05-15 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0020_remove_namedpoint_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summit',
            name='encirclement_parent',
        ),
    ]
