# Generated by Django 6.0.6 on 2026-06-17 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0021_remove_summit_encirclement_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='summit',
            name='horizon_parent_std',
            field=models.ForeignKey(blank=True, help_text='The summit that is the highest point above the local horizon with standard coefficient of refraction (0.14)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horizon_children_std', to='mountains.summit'),
        ),
        migrations.AlterField(
            model_name='col',
            name='point',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='col', to='mountains.namedpoint'),
        ),
        migrations.AlterField(
            model_name='river',
            name='source',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mountains.namedpoint'),
        ),
        migrations.AlterField(
            model_name='river',
            name='summit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rivers', to='mountains.summit'),
        ),
    ]
