# Generated by Django 6.0.6 on 2026-06-29 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0022_summit_horizon_parent_std_alter_col_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='river',
            name='branches_off',
            field=models.ForeignKey(blank=True, default=None, help_text='Set if the source is a branch off another river', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='mountains.river'),
        ),
        migrations.AlterField(
            model_name='river',
            name='summit',
            field=models.ForeignKey(blank=True, help_text='Nearest up-slope summit to the source', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rivers', to='mountains.summit'),
        ),
    ]
