# Generated by Django 6.0.6 on 2026-06-29 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0023_river_branches_off_alter_river_summit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summit',
            name='key_col',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='key_for', to='mountains.col'),
        ),
    ]
