# Generated by Django 6.0.6 on 2026-07-19 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0024_alter_summit_key_col'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='col',
            options={'ordering': ['point__altitude']},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['quality']},
        ),
    ]
