# Generated by Django 6.0.6 on 2026-08-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0025_alter_col_options_alter_source_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='river',
            name='mouth_side',
            field=models.CharField(blank=True, choices=[('L', 'left'), ('R', 'right'), ('O', 'other')], max_length=1, null=True),
        ),
    ]
