# Generated by Django 6.1 on 2026-09-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0026_river_mouth_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='summit',
            name='horizon_computed',
            field=models.DateTimeField(blank=True, help_text='When the horizon parent was last computed', null=True),
        ),
        migrations.AddField(
            model_name='summit',
            name='horizon_std_computed',
            field=models.DateTimeField(blank=True, help_text='When the horizon parent (std) was last computed', null=True),
        ),
        migrations.AddField(
            model_name='summit',
            name='slope_computed',
            field=models.DateTimeField(blank=True, help_text='When the slope parent was last computed', null=True),
        ),
    ]
