# Generated by Django 6.1 on 2026-09-12 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0027_summit_horizon_computed_summit_horizon_std_computed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='river',
            name='parent_summit',
            field=models.ForeignKey(blank=True, help_text='Highest summit within the watershed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drains', to='mountains.summit'),
        ),
        migrations.AlterField(
            model_name='river',
            name='mouth_side',
            field=models.CharField(blank=True, choices=[('L', 'left'), ('R', 'right'), ('O', 'other'), ('N', 'none')], max_length=1, null=True),
        ),
    ]
