# Generated by Django 6.1 on 2026-09-12 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0028_river_parent_summit_alter_river_mouth_side'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='river',
            name='summit',
        ),
        migrations.AddField(
            model_name='river',
            name='source_summit',
            field=models.ForeignKey(blank=True, help_text='Dominant up-slope summit from the source', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rivers', to='mountains.summit'),
        ),
    ]
