# Generated by Django 6.1 on 2026-09-12 14:54

from django.db import migrations, models


def n_to_s(apps, schema_editor):
    River = apps.get_model('mountains', 'River')
    River.objects.filter(mouth_side='N').update(mouth_side='S')


def s_to_n(apps, schema_editor):
    River = apps.get_model('mountains', 'River')
    River.objects.filter(mouth_side='S').update(mouth_side='N')


class Migration(migrations.Migration):
    """
    Rename the 'none' mouth side to 'sea', code 'N' -> 'S'.

    `makemigrations` writes the `AlterField` alone, which would leave every stored 'N'
    behind as a value outside the field's own choices — the same way 0029 dropped the
    `summit` column's data. The `RunPython` moves the rows too, and reverses cleanly so
    the migration can be rolled back.
    """

    dependencies = [
        ('mountains', '0029_remove_river_summit_river_source_summit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='river',
            name='mouth_side',
            field=models.CharField(blank=True, choices=[('L', 'left'), ('R', 'right'), ('O', 'other'), ('S', 'sea')], max_length=1, null=True),
        ),
        migrations.RunPython(n_to_s, s_to_n),
    ]
