# Generated by Django 6.1 on 2026-09-12 18:09

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0030_alter_river_mouth_side'),
    ]

    operations = [
        migrations.CreateModel(
            name='RangeSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="URL-safe identifier: 'sk-geomorf', 'soiusa', 'ave'", max_length=32, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='range_systems', to='mountains.source')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level_name', models.CharField(blank=True, max_length=64, null=True)),
                ('path', models.CharField(db_collation='C', db_index=True, default='', editable=False, max_length=255)),
                ('area', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, geography=True, null=True, srid=4326)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='mountains.range')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ranges', to='mountains.rangesystem')),
            ],
            options={
                'ordering': ['system', 'path'],
            },
        ),
        migrations.CreateModel(
            name='SummitRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='mountains.range')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='range_memberships', to='mountains.source')),
                ('summit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='range_memberships', to='mountains.summit')),
                ('system', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mountains.rangesystem')),
            ],
        ),
        migrations.AddConstraint(
            model_name='range',
            constraint=models.UniqueConstraint(fields=('system', 'parent', 'name'), name='unique_range_name_per_parent', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='range',
            constraint=models.CheckConstraint(condition=models.Q(('path', ''), ('path__endswith', '.'), _connector='OR'), name='range_path_is_dot_terminated'),
        ),
        migrations.AddConstraint(
            model_name='summitrange',
            constraint=models.UniqueConstraint(fields=('summit', 'system'), name='one_range_per_system_per_summit'),
        ),
    ]
