# Generated by Django 6.1 on 2026-09-14 15:48, then rewritten by hand — see the docstring.

import django.db.models.deletion
from django.db import migrations, models


def carry_the_point_across(apps, schema_editor):
    """
    `parent_summit` -> `watershed_high_point`, following `Summit.point`.

    Refuses rather than guesses. `Summit.point` is nullable, and a summit without one has no
    point to carry across; writing NULL would be indistinguishable from "nobody recorded a
    high point", and the `RemoveField` below would then destroy the only evidence of what it
    should have been. Raising is safe because the whole migration is one transaction on
    PostgreSQL, so a refusal rolls the new column back too and leaves the schema untouched.
    """
    River = apps.get_model('mountains', 'River')
    Summit = apps.get_model('mountains', 'Summit')

    # `order_by()` because `Summit.Meta.ordering` is ('-point__altitude',) and survives into
    # migration state, which would drag a pointless join into this query.
    points = dict(Summit.objects.order_by().values_list('pk', 'point_id'))
    rivers = list(River.objects.filter(parent_summit__isnull=False))

    pointless = sorted({river.parent_summit_id for river in rivers
                        if points.get(river.parent_summit_id) is None})
    if pointless:
        raise RuntimeError(
            f'cannot map watershed high points: summits {pointless} have no point. '
            f'Give them one, or clear the rivers that name them, then migrate again.'
        )

    for river in rivers:
        river.watershed_high_point_id = points[river.parent_summit_id]
    River.objects.bulk_update(rivers, ['watershed_high_point'])


def carry_the_summit_back(apps, schema_editor):
    """
    The reverse, lossy on purpose.

    A high point that is not a summit has no summit to go back to and reverts to NULL —
    which is the whole capability this migration adds, so the loss grows with use. Right
    after 0032 is applied the reverse is exact, because every value came from a summit.
    `Summit.point` is a one-to-one, so where a summit does exist there is never a choice
    between two.
    """
    River = apps.get_model('mountains', 'River')
    Summit = apps.get_model('mountains', 'Summit')

    summits = dict(Summit.objects.order_by()
                   .exclude(point__isnull=True)
                   .values_list('point_id', 'pk'))
    rivers = list(River.objects.filter(watershed_high_point__isnull=False))
    for river in rivers:
        river.parent_summit_id = summits.get(river.watershed_high_point_id)
    River.objects.bulk_update(rivers, ['parent_summit'])


class Migration(migrations.Migration):
    """
    Retarget the watershed high point from `Summit` to `NamedPoint`, and rename it.

    `makemigrations` writes `RemoveField` then `AddField`, which drops the old column and
    its 50 values before anything can read them — the same way 0029 lost `River.summit` and
    had to be repaired by hand from a backup. Here the new column is added *first*, the
    values are carried across, and only then is the old one dropped.

    An `AlterField` would have been worse than useless: it keeps the column and reinterprets
    Summit pks as NamedPoint pks. Of the 40 distinct summits in use, 26 are also valid
    NamedPoint ids — those rows would silently point at an unrelated place — and the other
    14 would abort on the new foreign key. The values have to be rewritten, not relabelled.

    No `RenameField` is needed: the field is being renamed anyway, so adding under the new
    name and dropping the old one does both jobs at once.
    """

    dependencies = [
        ('mountains', '0031_rangesystem_range_summitrange_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='river',
            name='watershed_high_point',
            field=models.ForeignKey(blank=True, help_text='Highest point within the watershed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drains', to='mountains.namedpoint'),
        ),
        # elidable=False (the default, spelled out): a later squashmigrations must not be
        # allowed to collapse 0028's AddField with the RemoveField below and drop the copy.
        migrations.RunPython(carry_the_point_across, carry_the_summit_back, elidable=False),
        migrations.RemoveField(
            model_name='river',
            name='parent_summit',
        ),
    ]
